// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/askiada/external-sort-v2/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MockChunkCreator is an autogenerated mock type for the ChunkCreator type
type MockChunkCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, input, chunks, chunkMemory
func (_m *MockChunkCreator) Create(ctx context.Context, input model.Reader, chunks chan<- model.Reader, chunkMemory int64) error {
	ret := _m.Called(ctx, input, chunks, chunkMemory)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Reader, chan<- model.Reader, int64) error); ok {
		r0 = rf(ctx, input, chunks, chunkMemory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MaxMemory provides a mock function with given fields:
func (_m *MockChunkCreator) MaxMemory() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxMemory")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// SyncCreate provides a mock function with given fields: ctx, input, chunks, chunkMemory
func (_m *MockChunkCreator) SyncCreate(ctx context.Context, input model.Reader, chunks chan<- model.Reader, chunkMemory int64) error {
	ret := _m.Called(ctx, input, chunks, chunkMemory)

	if len(ret) == 0 {
		panic("no return value specified for SyncCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Reader, chan<- model.Reader, int64) error); ok {
		r0 = rf(ctx, input, chunks, chunkMemory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockChunkCreator creates a new instance of MockChunkCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunkCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunkCreator {
	mock := &MockChunkCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
