// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/askiada/external-sort-v2/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MockChunkSorter is an autogenerated mock type for the ChunkSorter type
type MockChunkSorter struct {
	mock.Mock
}

// Sort provides a mock function with given fields: ctx, rdr
func (_m *MockChunkSorter) Sort(ctx context.Context, rdr model.Reader) (model.Reader, error) {
	ret := _m.Called(ctx, rdr)

	if len(ret) == 0 {
		panic("no return value specified for Sort")
	}

	var r0 model.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Reader) (model.Reader, error)); ok {
		return rf(ctx, rdr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Reader) model.Reader); ok {
		r0 = rf(ctx, rdr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Reader) error); ok {
		r1 = rf(ctx, rdr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockChunkSorter creates a new instance of MockChunkSorter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunkSorter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunkSorter {
	mock := &MockChunkSorter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
