// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTracker is an autogenerated mock type for the Tracker type
type MockTracker struct {
	mock.Mock
}

// NewMockTracker creates a new instance of MockTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracker {
	mock := &MockTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
