// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	regexp "regexp"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"

	s3handler "github.com/askiada/external-sort-v2/examples/s3handler"

	types "github.com/aws/aws-sdk-go-v2/service/s3/types"
)

// MockS3Client is an autogenerated mock type for the S3Client type
type MockS3Client struct {
	mock.Mock
}

// Download provides a mock function with given fields: ctx, bucket, key, wr
func (_m *MockS3Client) Download(ctx context.Context, bucket string, key string, wr io.Writer) error {
	ret := _m.Called(ctx, bucket, key, wr)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Writer) error); ok {
		r0 = rf(ctx, bucket, key, wr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, bucket, key, pattern
func (_m *MockS3Client) Find(ctx context.Context, bucket string, key string, pattern *regexp.Regexp) ([]types.Object, error) {
	ret := _m.Called(ctx, bucket, key, pattern)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []types.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *regexp.Regexp) ([]types.Object, error)); ok {
		return rf(ctx, bucket, key, pattern)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *regexp.Regexp) []types.Object); ok {
		r0 = rf(ctx, bucket, key, pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *regexp.Regexp) error); ok {
		r1 = rf(ctx, bucket, key, pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HeadObject provides a mock function with given fields: ctx, bucket, key
func (_m *MockS3Client) HeadObject(ctx context.Context, bucket string, key string) (*s3.HeadObjectOutput, error) {
	ret := _m.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for HeadObject")
	}

	var r0 *s3.HeadObjectOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*s3.HeadObjectOutput, error)); ok {
		return rf(ctx, bucket, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *s3.HeadObjectOutput); ok {
		r0 = rf(ctx, bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.HeadObjectOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Stream provides a mock function with given fields: ctx, bucket, key, processFn
func (_m *MockS3Client) Stream(ctx context.Context, bucket string, key string, processFn s3handler.ProcessStream) error {
	ret := _m.Called(ctx, bucket, key, processFn)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, s3handler.ProcessStream) error); ok {
		r0 = rf(ctx, bucket, key, processFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upload provides a mock function with given fields: ctx, bucket, key, rdr
func (_m *MockS3Client) Upload(ctx context.Context, bucket string, key string, rdr io.Reader) error {
	ret := _m.Called(ctx, bucket, key, rdr)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) error); ok {
		r0 = rf(ctx, bucket, key, rdr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadByte provides a mock function with given fields: ctx, bucket, key, body
func (_m *MockS3Client) UploadByte(ctx context.Context, bucket string, key string, body []byte) error {
	ret := _m.Called(ctx, bucket, key, body)

	if len(ret) == 0 {
		panic("no return value specified for UploadByte")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, bucket, key, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockS3Client creates a new instance of MockS3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Client {
	mock := &MockS3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
